Resources:
  OrganizationAccountAccessRole:
    Type: "AWS::IAM::Role"
    # Let's not lock us out the org.
    DeletionPolicy: Retain
    Properties:
      RoleName: OrganizationAccountAccessRole
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::349603509961:root"
            },
            "Action": "sts:AssumeRole",
            "Condition": {}
          }
        ]
      }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # FIXME: Need to get finer grained with the IAM management permissions. Doing this for now.
  OrganizationAccountAccessUserRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: OrganizationAccountAccessUserRole
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::349603509961:root"
            },
            "Action": "sts:AssumeRole",
            "Condition": {}
          }
        ]
      }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AWSXrayFullAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      Policies:
        - PolicyName: "IamRoleManage"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "iam:AttachRolePolicy"
                  - "iam:CreatePolicy"
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:DeleteRolePolicy"
                  - "iam:PassRole"
                  - "iam:PutRolePolicy"
                  - "iam:DetachRolePolicy"
                Resource: "*"

        - PolicyName: "CloudFormationFullAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "CloudFormation:*"
                Resource: "*"
        - PolicyName: "Route53Zones"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "route53:CreateHostedZone"
                  - "route53:UpdateHostedZoneComment"
                  - "route53:GetHostedZone"
                  - "route53:ListHostedZones"
                  - "route53:DeleteHostedZone"
                  - "route53:ChangeResourceRecordSets"
                  - "route53:GetChange"
                  - "route53:ListResourceRecordSets"
                  - "route53:GetHostedZoneCount"
                  - "route53:ListHostedZonesByName"
                  - "route53:CreateHealthCheck"
                  - "route53:UpdateHealthCheck"
                  - "route53:GetHealthCheck"
                  - "route53:ListHealthChecks"
                  - "route53:DeleteHealthCheck"
                  - "route53:GetCheckerIpRanges"
                  - "route53:GetHealthCheckCount"
                  - "route53:GetHealthCheckStatus"
                  - "route53:GetHealthCheckLastFailureReason"
                Resource: "*"

  OrganizationAccountAccessAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: OrganizationAccountAccessAdminRole
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::349603509961:root"
            },
            "Action": "sts:AssumeRole",
            "Condition": {}
          }
        ]
      }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

