Resources:
  tomAdmin:
    Type: "AWS::IAM::User"
    DeletionPolicy: Retain
    Properties:
      Groups:
        - PrimeAdmins
        - CICDAdmins
        - DevAdmins
        - ProdAdmins
        - TrainingAdmins
      UserName: tom-admin

  tom:
    Type: "AWS::IAM::User"
    DeletionPolicy: Retain
    Properties:
      Groups:
        - PrimePowerUsers
        - PrimeUsers
        - CICDUsers
        - DevUsers
        - ProdUsers
      UserName: tom


