Resources:
  tomAdmin:
    Type: "AWS::IAM::User"
    Properties:
      Groups:
        - PrimeAdmins
        - DevAdmins
        - ProdAdmins
        - TrainingAdmins
      UserName: tom-admin
  tom:
    Type: "AWS::IAM::User"
    Properties:
      Groups:
        - PrimePowerUsers
        - PrimeUsers
        - DevUsers
        - ProdUsers
      UserName: tom

