Resources:
  tomAdmin:
    Type: "AWS::IAM::User"
    Properties:
      Groups:
        - FullAdmins
        - DevAdmins
      UserName: tom-admin
  tom:
    Type: "AWS::IAM::User"
    Properties:
      Groups:
        - Admins
        - Users
        - DevUsers
      UserName: tom

