# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: iam-users-training

# NOTE: Password policy cannot be set with CFN resources. One day maybe
# investigate the following:
# https://github.com/widdix/aws-cf-templates/blob/master/security/account-password-policy.yaml

# FIXME: How do we remove users? By default the resources are retained in the
# stack.

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  stage: ${opt:stage, env:SLS_STAGE, 'dev'}
  profile: ${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, 'default'}

resources: ${file(./${self:provider.stage}.yml)}
