Resources:
  PrimeAdmins:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: PrimeAdmins
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  PrimeUsers:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: PrimeUsers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  DevUsers:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: DevUsers
      ManagedPolicyArns:
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevUsersPolicyArn
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev1UsersPolicyArn
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev2UsersPolicyArn

  DevAdmins:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: DevAdmins
      ManagedPolicyArns:
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevAdminPolicyArn

  ProdUsers:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: ProdUsers
      ManagedPolicyArns:
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdUsersPolicyArn

  ProdAdmins:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: ProdAdmins
      ManagedPolicyArns:
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdAdminPolicyArn


  # CI/CD deployment
  DevDeploy:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: DevDeploy
      ManagedPolicyArns:
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevDeployPolicyArn

  ProdDeploy:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: ProdDeploy
      ManagedPolicyArns:
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdDeployPolicyArn

