# Manage IAM users, groups, policies, and roles.
service: iam-parent

plugins:
  - serverless-parameters
  - serverless-aws-nested-stacks


custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  nested-stacks:
    location: "accounts/${self:custom.stage}"
    stacks: "${file(./accounts/${self:custom.stage}/stack-conf.yml)}"


provider:
  name: aws
  stage: "${self:custom.stage}"
  stackTags:
    x-service: "${self:service}"
    x-stack: "${self:service}-${self:provider.stage}"



