Parameters:
  TrustedAccountId:
    Type: Number
    Description: "Account ID of trusted account to grant role access"

  RoleNamePrefix:
    Type: String
    Description: "IAM role name prefix"

  InitDeploy:
    Type: String
    Description: "Whether this is an initial deployment or not."


Conditions:
  IsNotInitDeploy:
    Fn::Equals:
      - Ref: InitDeploy
      - false


Resources:
  OrganizationAccountAccessRole:
    Type: "AWS::IAM::Role"
    # Let's not lock us out the org.
    DeletionPolicy: Retain
    Condition: IsNotInitDeploy
    Properties:
      RoleName:
        Fn::Sub: "${RoleNamePrefix}AccessRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                Fn::Sub: "arn:aws:iam::${TrustedAccountId}:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  OrganizationAccountAccessUserRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: "${RoleNamePrefix}AccessUserRole"
      MaxSessionDuration: 21600
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                Fn::Sub: "arn:aws:iam::${TrustedAccountId}:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
        - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
        - arn:aws:iam::aws:policy/AWSHealthFullAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonRoute53ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Policies:
        - PolicyName: "IamRoleManage"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource: "*"
        - PolicyName: "Account"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "Account"
                Effect: "Allow"
                Action:
                  - "account:Get*"
                  - "account:List*"
                Resource: "*"
              - Sid: "AccountActivity"
                Effect: "Allow"
                Action:
                  - "aws-portal:ViewBilling"
                Resource: "*"
              - Sid: "Organizations"
                Effect: "Allow"
                Action:
                  - "organizations:Describe*"
                  - "organizations:List*"
                Resource: "*"
        - PolicyName: "CloudFormationFullAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "CloudFormation:*"
                Resource: "*"
        - PolicyName: "KmsRead"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "kms:List*"
                  - "kms:Describe*"
                Resource: "*"
        - PolicyName: "StepFunctions"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "kms:Get*"
                  - "kms:Describe*"
                  - "kms:List*"
                Resource: "*"
        - PolicyName: "XRay"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "xray:Get*"
                  - "xray:BatchGet*"
                  - "xray:List*"
                Resource: "*"


  OrganizationAccountAccessAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: "${RoleNamePrefix}AccessAdminRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                Fn::Sub: "arn:aws:iam::${TrustedAccountId}:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess


