Parameters:
  TrustedAccountId:
    Type: Number
    Description: "Account ID of trusted account to grant role access"

  RoleNamePrefix:
    Type: String
    Description: "IAM role name prefix"

  InitDeploy:
    Type: String
    Description: "Whether this is an initial deployment or not."

  DeployRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "Deployment IAM role ARN"
    Default: "/infra/deploy/prime/DeployRoleArn"


Conditions:
  IsNotInitDeploy:
    Fn::Equals:
      - Ref: InitDeploy
      - false


Resources:
  OrganizationAccountAccessRole:
    Type: "AWS::IAM::Role"
    # Let's not lock us out the org.
    DeletionPolicy: Retain
    Condition: IsNotInitDeploy
    Properties:
      RoleName:
        Fn::Sub: "${RoleNamePrefix}AccessRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                Fn::Sub: "arn:aws:iam::${TrustedAccountId}:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  OrganizationAccountAccessUserRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: "${RoleNamePrefix}AccessUserRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                Fn::Sub: "arn:aws:iam::${TrustedAccountId}:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSXrayReadOnlyAccess
      Policies:
        - PolicyName: "IamRoleManage"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource: "*"
        - PolicyName: "CloudFormationFullAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "CloudFormation:*"
                Resource: "*"
        - PolicyName: "KmsRead"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "kms:List*"
                  - "kms:Describe*"
                Resource: "*"

  OrganizationAccountAccessAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: "${RoleNamePrefix}AccessAdminRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                Fn::Sub: "arn:aws:iam::${TrustedAccountId}:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess


