Resources:
  ServerlessOps:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "serverlessops.io"
      HostedZoneConfig:
        Comment: ServerlessOps

  ServerlessOpsRR:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      Comment: "Apex Records"
      HostedZoneId:
        Ref: ServerlessOps
      RecordSets:
        - Name: "serverlessops.io."
          Type: "MX"
          TTL: 300
          ResourceRecords:
            - 1 aspmx.l.google.com
            - 5 alt1.aspmx.l.google.com
            - 5 alt2.aspmx.l.google.com
            - 10 alt3.aspmx.l.google.com
            - 10 alt4.aspmx.l.google.com
            - 15 n2235kmtje5chj5uz63i3sluem7gtehtp5dlmladr2nfntojbqpq.mx-verification.google.com.
        - Name: "serverlessops.io"
          Type: "TXT"
          TTL: 14400
          ResourceRecords:
            - "\"v=spf1 include:_spf.google.com include:277116.spf08.hubspotemail.net ~all\""

  ServerlessOpsDomainSsmParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/${self:service}/root/ServerlessOpsDomain"
      Type: String
      Value: "serverlessops.io"

  ServerlessOpsWww:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Website"
      HostedZoneId:
        Ref: ServerlessOps
      Name: "www.serverlessops.io."
      Type: "CNAME"
      TTL: 3600
      ResourceRecords:
        - 277116.group16.sites.hubspot.net

  ServerlessOpsDev:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Dev domain delegation"
      HostedZoneId:
        Ref: ServerlessOps
      Name: "dev.serverlessops.io."
      Type: "NS"
      TTL: 86400
      ResourceRecords:
        - ns-1418.awsdns-49.org
        - ns-953.awsdns-55.net
        - ns-1850.awsdns-39.co.uk
        - ns-64.awsdns-08.com

  ServerlessOpsProd:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Prod domain delegation"
      HostedZoneId:
        Ref: ServerlessOps
      Name: "prod.serverlessops.io."
      Type: "NS"
      TTL: 86400
      ResourceRecords:
        - ns-1587.awsdns-06.co.uk
        - ns-1356.awsdns-41.org
        - ns-667.awsdns-19.net
        - ns-151.awsdns-18.com

  ServerlessOpsTraining:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Prod domain delegation"
      HostedZoneId:
        Ref: ServerlessOps
      Name: "training.serverlessops.io."
      Type: "NS"
      TTL: 86400
      ResourceRecords:
        - ns-747.awsdns-29.net
        - ns-1951.awsdns-51.co.uk
        - ns-1097.awsdns-09.org
        - ns-152.awsdns-19.com

  ServerlessOpsDomainKeyHs1:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "HubSpot domain key"
      HostedZoneId:
        Ref: ServerlessOps
      Name: "hs1._domainkey.serverlessops.io."
      Type: "CNAME"
      TTL: 3600
      ResourceRecords:
        - serverlessops-io.hs01a.dkim.hubspotemail.net

  ServerlessOpsDomainKeyHs2:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "HubSpot domain key"
      HostedZoneId:
        Ref: ServerlessOps
      Name: "hs2._domainkey.serverlessops.io."
      Type: "CNAME"
      TTL: 3600
      ResourceRecords:
        - serverlessops-io.hs01b.dkim.hubspotemail.net

  ServerlessOpsDomainKeySmtpapi:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "HubSpot domain key"
      HostedZoneId:
        Ref: ServerlessOps
      Name: "smtpapi._domainkey.serverlessops.io."
      Type: "TXT"
      TTL: 3600
      # Those escape secquences are necessary.
      ResourceRecords:
        - "\"k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDPtW5iwpXVPiH5FzJ7Nrl8USzuY9zqqzjE0D1r04xDN6qwziDnmgcFNNfMewVKN2D1O+2J9N14hRprzByFwfQW76yojh54Xu3uSbQ3JP0A7k8o8GutRF8zbFUA8n0ZH2y0cIEjMliXY4W4LwPA7m4q0ObmvSjhd63O9d8z1XkUBwIDAQAB\""

  ServerlessOpsCom:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "serverless-ops.com"
      HostedZoneConfig:
        Comment: Serverless-Ops.com

  ServerlessOpsComWww:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Website"
      HostedZoneId:
        Ref: ServerlessOpsCom
      Name: "www.serverless-ops.com."
      Type: "CNAME"
      TTL: 3600
      ResourceRecords:
        - 277116.group16.sites.hubspot.net

  ServerlessDevOpsCom:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "serverless-devops.com"
      HostedZoneConfig:
        Comment: Serverless-DevOps.com

  ServerlessDevOpsComWww:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Website"
      HostedZoneId:
        Ref: ServerlessDevOpsCom
      Name: "www.serverless-devops.com."
      Type: "CNAME"
      TTL: 3600
      ResourceRecords:
        - 277116.group16.sites.hubspot.net

  ServerlessZomboCom:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "serverlesszombo.com"
      HostedZoneConfig:
        Comment: ServerlessZombo.com

  ServerlessDashZomboCom:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "serverless-zombo.com"
      HostedZoneConfig:
        Comment: "This... is... serverless. Welcome. This is serverless; welcome ... to serverless. You can do anything with serverless. Anything at all. The only limit is yourself. Welcome... to serverless"

Outputs:
  ServerlessOpsNameServers:
    Description: Hosted zone name servers
    Value:
      Fn::Join:
        - ','
        - Fn::GetAtt:
          - ServerlessOps
          - NameServers
    Export:
      Name: ${self:service}-${self:provider.stage}-ServerlessOpsNameServers

  ServerlessOpsComNameServers:
    Description: Hosted zone name servers
    Value:
      Fn::Join:
        - ','
        - Fn::GetAtt:
          - ServerlessOpsCom
          - NameServers
    Export:
      Name: ${self:service}-${self:provider.stage}-ServerlessOpsComNameServers

  ServerlessDevOpsComNameServers:
    Description: Hosted zone name servers
    Value:
      Fn::Join:
        - ','
        - Fn::GetAtt:
          - ServerlessDevOpsCom
          - NameServers
    Export:
      Name: ${self:service}-${self:provider.stage}-ServerlessDevOpsComNameServers

  ServerlessZomboComNameServers:
    Description: Hosted zone name servers
    Value:
      Fn::Join:
        - ','
        - Fn::GetAtt:
          - ServerlessZomboCom
          - NameServers
    Export:
      Name: ${self:service}-${self:provider.stage}-ServerlessZomboComNameServers

  ServerlessDashZomboComNameServers:
    Description: Hosted zone name servers
    Value:
      Fn::Join:
        - ','
        - Fn::GetAtt:
          - ServerlessDashZomboCom
          - NameServers
    Export:
      Name: ${self:service}-${self:provider.stage}-ServerlessDashZomboComNameServers

