Resources:
  # When creating a new subdomain you must update the parent domain with an NS
  # record and the values from this domain.
  ServerlessOpsTraining:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "training.serverlessops.io"
      HostedZoneConfig:
        Comment: ServerlessOps - Training Prime

  ServerlessOpsDevTraining:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Training Dev delegation"
      HostedZoneId:
        Ref: ServerlessOpsTraining
      Name: "dev.training.serverlessops.io."
      Type: "NS"
      TTL: 86400
      ResourceRecords:
        - ns-455.awsdns-56.com
        - ns-1072.awsdns-06.org
        - ns-1548.awsdns-01.co.uk
        - ns-576.awsdns-08.net

  ServerlessOpsDev1Training:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Training Dev delegation"
      HostedZoneId:
        Ref: ServerlessOpsTraining
      Name: "dev1.training.serverlessops.io."
      Type: "NS"
      TTL: 86400
      ResourceRecords:
        - ns-2024.awsdns-61.co.uk
        - ns-1200.awsdns-22.org
        - ns-894.awsdns-47.net
        - ns-483.awsdns-60.com

  ServerlessOpsDev2Training:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Training Dev delegation"
      HostedZoneId:
        Ref: ServerlessOpsTraining
      Name: "dev2.training.serverlessops.io."
      Type: "NS"
      TTL: 86400
      ResourceRecords:
        - ns-1139.awsdns-14.org
        - ns-826.awsdns-39.net
        - ns-1957.awsdns-52.co.uk
        - ns-37.awsdns-04.com

  ServerlessOpsProdTraining:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "Training Dev delegation"
      HostedZoneId:
        Ref: ServerlessOpsTraining
      Name: "prod.training.serverlessops.io."
      Type: "NS"
      TTL: 86400
      ResourceRecords:
        - ns-406.awsdns-50.com
        - ns-1496.awsdns-59.org
        - ns-585.awsdns-09.net
        - ns-1934.awsdns-49.co.uk

Outputs:
  ServerlessOpsDevNameServers:
    Description: Hosted zone name servers
    Value:
      Fn::Join:
        - ','
        - Fn::GetAtt:
          - ServerlessOpsTraining
          - NameServers
    Export:
      Name: ${self:service}-${self:provider.stage}-ServerlessOpsDevNameServers

