Resources:
  # When creating a new subdomain you must update the parent domain with an NS
  # record and the values from this domain.
  ServerlessOpsDev:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "dev.training.serverlessops.io"
      HostedZoneConfig:
        Comment: ServerlessOps - Training Dev

Outputs:
  ServerlessOpsDevNameServers:
    Description: Hosted zone name servers
    Value:
      Fn::Join:
        - ','
        - Fn::GetAtt:
          - ServerlessOpsDev
          - NameServers
    Export:
      Name: ${self:service}-${self:provider.stage}-ServerlessOpsDevNameServers

