Resources:
  # You still need the ability to carry out the resource actions in the template.
  CloudFormationFullAccess:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: CloudFormationFullAccess
      PolicyDocument: {
        "Version":"2012-10-17",
        "Statement":[
          {
            "Effect":"Allow",
            "Action": "cloudformation:*",
            "Resource":"*"
          }
        ]
      }


  ### DEV
  OrganizationAccountAccessServerlessOpsDevPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-dev
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.account_number_dev}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDevUsersPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-dev-Users
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.account_number_dev}:role/OrganizationAccountAccessUserRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDevAdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-dev-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.account_number_dev}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }


  ### PROD
  OrganizationAccountAccessServerlessOpsProdPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-prod
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.account_number_prod}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsProdUsersPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-prod-Users
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.account_number_prod}:role/OrganizationAccountAccessUserRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsProdAdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-prod-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.account_number_prod}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }

  ### TRAINING
  OrganizationAccountAccessServerlessOpsTrainingPrimePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-prime
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_prime}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsTrainingPrimeAdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-prime-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_prime}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }

  ### TRAINING DEV
  OrganizationAccountAccessServerlessOpsTrainingDevPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsTrainingDevAdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }

  ### TRAINING PROD
  OrganizationAccountAccessServerlessOpsTrainingProdPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-prod
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_prod}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsTrainingProdAdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-prod-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_prod}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }

Outputs:
  CloudFormationFullAccessArn:
    Description: Policy ARN
    Value:
      Ref: CloudFormationFullAccess
    Export:
      Name: ${self:service}-${self:provider.stage}-CloudFormationFullAccessArn

  ### DEV
  OrganizationAccountAccessServerlessOpsDevPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDevPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevPolicyArn
  OrganizationAccountAccessServerlessOpsDevUsersPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDevUsersPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevUsersPolicyArn
  OrganizationAccountAccessServerlessOpsDevAdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDevAdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevAdminPolicyArn

  ### PROD
  OrganizationAccountAccessServerlessOpsProdPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsProdPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdPolicyArn
  OrganizationAccountAccessServerlessOpsProdUsersPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsProdUsersPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdUsersPolicyArn
  OrganizationAccountAccessServerlessOpsProdAdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsProdAdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdAdminPolicyArn

  ### TRAINING PRIME
  OrganizationAccountAccessServerlessOpsTrainingPrimePolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsTrainingPrimePolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsTrainingPrimePolicyArn
  OrganizationAccountAccessServerlessOpsTrainingPrimeAdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsTrainingPrimeAdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsTrainingPrimeAdminPolicyArn

  ### TRAINING DEV
  OrganizationAccountAccessServerlessOpsTrainingDevPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsTrainingDevPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsTrainingDevPolicyArn
  OrganizationAccountAccessServerlessOpsTrainingDevAdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsTrainingDevAdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsTrainingDevAdminPolicyArn

  ### TRAINING PROD
  OrganizationAccountAccessServerlessOpsTrainingProdPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsTrainingProdPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsTrainingProdPolicyArn
  OrganizationAccountAccessServerlessOpsTrainingProdAdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsTrainingProdAdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsTrainingProdAdminPolicyArn

