Resources:
  # You still need the ability to carry out the resource actions in the template.
  CloudFormationFullAccess:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: CloudFormationFullAccess
      PolicyDocument: {
        "Version":"2012-10-17",
        "Statement":[
          {
            "Effect":"Allow",
            "Action": "cloudformation:*",
            "Resource":"*"
          }
        ]
      }

  ### DEV
  OrganizationAccountAccessServerlessOpsDevPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDevUsersPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev-Users
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev}:role/OrganizationAccountAccessUserRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDevAdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDevDeployPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev-Deploy
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev}:role/OrganizationAccountAccessDeployRole"
          }
        ]
      }


  ### DEV1
  OrganizationAccountAccessServerlessOpsDev1Policy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev1
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev1}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDev1UsersPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev1-Users
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev1}:role/OrganizationAccountAccessUserRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDev1AdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev1-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev1}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDev1DeployPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev1-Deploy
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev1}:role/OrganizationAccountAccessDeployRole"
          }
        ]
      }


  ### DEV2
  OrganizationAccountAccessServerlessOpsDev2Policy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev2
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev2}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDev2UsersPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev2-Users
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev2}:role/OrganizationAccountAccessUserRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDev2AdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev2-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev2}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsDev2DeployPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-dev2-Deploy
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_dev2}:role/OrganizationAccountAccessDeployRole"
          }
        ]
      }


  ### PROD
  OrganizationAccountAccessServerlessOpsProdPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-prod
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_prod}:role/OrganizationAccountAccessRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsProdUsersPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-prod-Users
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_prod}:role/OrganizationAccountAccessUserRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsProdAdminsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-prod-Admins
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_prod}:role/OrganizationAccountAccessAdminRole"
          }
        ]
      }

  OrganizationAccountAccessServerlessOpsProdDeployPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: OrganizationAccountAccess-serverlessops-training-prod-Deploy
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:assumeRole",
            "Resource": "arn:aws:iam::${self:custom.training_account_number_prod}:role/OrganizationAccountAccessDeployRole"
          }
        ]
      }



Outputs:
  CloudFormationFullAccessArn:
    Description: Policy ARN
    Value:
      Ref: CloudFormationFullAccess
    Export:
      Name: ${self:service}-${self:provider.stage}-CloudFormationFullAccessArn

  ### DEV
  OrganizationAccountAccessServerlessOpsDevPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDevPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevPolicyArn

  OrganizationAccountAccessServerlessOpsDevUsersPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDevUsersPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevUsersPolicyArn

  OrganizationAccountAccessServerlessOpsDevAdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDevAdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevAdminPolicyArn

  OrganizationAccountAccessServerlessOpsDevDeployPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDevDeployPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDevDeployPolicyArn

  ### DEV1
  OrganizationAccountAccessServerlessOpsDev1PolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDev1Policy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev1PolicyArn

  OrganizationAccountAccessServerlessOpsDev1UsersPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDev1UsersPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev1UsersPolicyArn

  OrganizationAccountAccessServerlessOpsDev1AdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDev1AdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev1AdminPolicyArn

  OrganizationAccountAccessServerlessOpsDev1DeployPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDev1DeployPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev1DeployPolicyArn

  ### DEV2
  OrganizationAccountAccessServerlessOpsDev2PolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDev2Policy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev2PolicyArn

  OrganizationAccountAccessServerlessOpsDev2UsersPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDev2UsersPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev2UsersPolicyArn

  OrganizationAccountAccessServerlessOpsDev2AdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDev2AdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev2AdminPolicyArn

  OrganizationAccountAccessServerlessOpsDev2DeployPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsDev2DeployPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsDev2DeployPolicyArn

  ### PROD
  OrganizationAccountAccessServerlessOpsProdPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsProdPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdPolicyArn

  OrganizationAccountAccessServerlessOpsProdUsersPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsProdUsersPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdUsersPolicyArn

  OrganizationAccountAccessServerlessOpsProdAdminPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsProdAdminsPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdAdminPolicyArn

  OrganizationAccountAccessServerlessOpsProdDeployPolicyArn:
    Description: Policy ARN
    Value:
      Ref: OrganizationAccountAccessServerlessOpsProdDeployPolicy
    Export:
      Name: ${self:service}-${self:provider.stage}-OrganizationAccountAccessServerlessOpsProdDeployPolicyArn

