# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: vpc-training

plugins:
  - serverless-cloudformation-sub-variables

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  stage: ${opt:stage, env:SLS_STAGE, 'dev'}
  profile: ${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, 'default'}
  region: ${opt:region, 'us-east-2'}
  stackTags:
    x-service: ${self:service}
    x-stack: ${self:service}-${self:provider.stage}

custom:
  vpc:
    cidr: "10.1.0.0/16"
    public:
      subnet1: "10.1.0.0/20"
      subnet2: "10.1.16.0/20"
      subnet3: "10.1.32.0/20"

resources:
  Resources:
    Vpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: "${self:custom.vpc.cidr}"
        EnableDnsHostnames: true
        EnableDnsSupport: true


    InternetGateway:
        Type: AWS::EC2::InternetGateway

    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId:
              Ref: InternetGateway
            VpcId:
              Ref: Vpc

    PublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
          VpcId:
            Ref: Vpc

    DefaultPublicRoute:
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties:
            RouteTableId:
              Ref: PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId:
              Ref: InternetGateway

    PublicSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId:
              Ref: Vpc
            AvailabilityZone:
              Fn::Select:
                - 0
                - Fn::GetAZs: ""
            CidrBlock: "${self:custom.vpc.public.subnet1}"
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value:
                    Fn::Sub:
                      - "Public Subnet (AZ - #{AZ})"
                      - AZ:
                          Fn::Select:
                            - 0
                            - Fn::GetAZs: ""
                - Key: AZ
                  Value:
                    Fn::Select:
                      - 0
                      - Fn::GetAZs: ""

    PublicSubnet1SSMParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: "/${self:service}/${self:provider.stage}/PublicSubnet1Id"
        Description: "Public Subnet 1 Id"
        Type: "String"
        Value:
          Ref: PublicSubnet1

    PublicSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId:
              Ref: PublicRouteTable
            SubnetId:
              Ref: PublicSubnet1

    PublicSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId:
              Ref: Vpc
            AvailabilityZone:
              Fn::Select:
                - 1
                - Fn::GetAZs: ""
            CidrBlock: "${self:custom.vpc.public.subnet2}"
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value:
                    Fn::Sub:
                      - "Public Subnet (AZ - #{AZ})"
                      - AZ:
                          Fn::Select:
                            - 1
                            - Fn::GetAZs: ""
                - Key: AZ
                  Value:
                    Fn::Select:
                      - 1
                      - Fn::GetAZs: ""

    PublicSubnet2SSMParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: "/${self:service}/${self:provider.stage}/PublicSubnet2Id"
        Description: "Public Subnet 2 Id"
        Type: "String"
        Value:
          Ref: PublicSubnet2

    PublicSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId:
              Ref: PublicRouteTable
            SubnetId:
              Ref: PublicSubnet2

    PublicSubnet3:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId:
              Ref: Vpc
            AvailabilityZone:
              Fn::Select:
                - 2
                - Fn::GetAZs: ""
            CidrBlock: "${self:custom.vpc.public.subnet3}"
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value:
                    Fn::Sub:
                      - "Public Subnet (AZ - #{AZ})"
                      - AZ:
                          Fn::Select:
                            - 2
                            - Fn::GetAZs: ""
                - Key: AZ
                  Value:
                    Fn::Select:
                      - 2
                      - Fn::GetAZs: ""

    PublicSubnet3SSMParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: "/${self:service}/${self:provider.stage}/PublicSubnet3Id"
        Description: "Public Subnet 3 Id"
        Type: "String"
        Value:
          Ref: PublicSubnet3

    PublicSubnet3RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId:
              Ref: PublicRouteTable
            SubnetId:
              Ref: PublicSubnet3

    SshSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow http to client host
        VpcId:
          Ref: Vpc
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 127.0.0.1/32

    AwsApiSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow AWS Api access.
        VpcId:
          Ref: Vpc
        SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 127.0.0.1/32
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

    SshSecurityGroupSSMParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: "/${self:service}/${self:provider.stage}/SshSecurityGroupId"
        Description: "SSH Security group Id"
        Type: "String"
        Value:
          Ref: SshSecurityGroup

    AwsApiSecurityGroupSSMParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: "/${self:service}/${self:provider.stage}/AwsApiSecurityGroupId"
        Description: "AWS API Security group Id"
        Type: "String"
        Value:
          Ref: AwsApiSecurityGroup

    DefaultSecurityGroupSSMParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: "/${self:service}/${self:provider.stage}/DefaultSecurityGroupId"
        Description: "Default Security Group"
        Type: "String"
        Value:
          Fn::GetAtt:
            - Vpc
            - DefaultSecurityGroup

  Outputs:
    DefaultSecurityGroupIdSSMParam:
      Description: Default security group ID
      Value:
        Ref: DefaultSecurityGroupSSMParam
      Export:
        Name: "${self:service}-${self:provider.stage}-DefaultSecurityGroupIdSSMParam"

    SshSecurityGroupIdSSMParam:
      Description: SSH security group ID
      Value:
        Ref: SshSecurityGroupSSMParam
      Export:
        Name: "${self:service}-${self:provider.stage}-SshSecurityGroupIdSSMParam"

    AwsApiSecurityGroupIdSSMParam:
      Description: AWS API security group ID
      Value:
        Ref: AwsApiSecurityGroupSSMParam
      Export:
        Name: "${self:service}-${self:provider.stage}-AwsApiSecurityGroupIdSSMParam"

    PublicSubnet1IdSSMParam:
      Description: Public subnet 1 ID
      Value:
        Ref: PublicSubnet1SSMParam
      Export:
        Name: "${self:service}-${self:provider.stage}-PublicSubnet1IdSSMParam"

    PublicSubnet2IdSSMParam:
      Description: Public subnet 2 ID
      Value:
        Ref: PublicSubnet2SSMParam
      Export:
        Name: "${self:service}-${self:provider.stage}-PublicSubnet2IdSSMParam"

    PublicSubnet3IdSSMParam:
      Description: Public subnet 3 ID
      Value:
        Ref: PublicSubnet1SSMParam
      Export:
        Name: "${self:service}-${self:provider.stage}-PublicSubnet3IdSSMParam"

