service: container-registry

provider:
  name: aws
  stage: ${opt:stage, env:SLS_STAGE, 'dev'}
  profile: ${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, 'default'}
  region: ${opt:region, 'us-east-2'}

resources:
  Resources:
    Repository:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: "serverlessops-training"
        RepositoryPolicyText:
          Version: "2012-10-17"
          Statement:
            - Sid: AllowPull
              Effect: Allow
              Principal:
                AWS: "*"
              Action:
                - "ecr:GetDownloadUrlForLayer"
                - "ecr:BatchGetImage"
                - "ecr:BatchCheckLayerAvailability"
                - "ecr:DescribeImages"
                - "ecr:DescribeRepositories"
  Outputs:
    RepositoryId:
      Description: ECR Repo ID
      Value:
        Ref: Repository
      Export:
        Name: "${self:service}-${self:provider.stage}-RepositoryId"


